#

logging:
  level:
    root: INFO
    com.haselt.debtcollecting.web: DEBUG
    org.springframework.security: DEBUG
    org:
      hibernate:
        # Set Statistics level
        stat: debug
        SQL: debug
        type:
          descriptor:
            sql: trace

spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/debtcollectorapp
    username: debtcollectorapp
    password: debtcollector@haselt
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      generate-ddl: false
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    #Turn Statistics on
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        generate_statistics: true